config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  # Associations list
  get 'assos' => 'assos#index', as: :assos

  # Specific asso details
  get 'asso/:id(/page/:page)' => 'assos#show',   as: :asso
  put 'asso/:id'              => 'assos#update', as: :update_asso
  get 'asso/:id/edit'         => 'assos#edit',   as: :edit_asso

  # Asso blog
  resources :blog_posts, path: 'posts'

  # Partners
  get    'partners'          => 'partners#index', as: :partners
  post   'partners'          => 'partners#create'
  put    'partners/:id'      => 'partners#update',  as: :partner
  delete 'partners/:id'      => 'partners#destroy'
  get    'partners/new'      => 'partners#new',     as: :new_partner
  get    'partners/:id/edit' => 'partners#edit',    as: :edit_partner

  # Asso events
  get 'events/calendar'              => 'events#calendar',    as: :events_calendar
  get 'asso/:id/events(/page/:page)' => 'events#asso_events', as: :asso_events
  resources :events do
    get 'page/:page', :action => :index, :on => :collection
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    # Disable user signup
    # get    "signup"  => "users/registrations#new",    as: :new_user_registration
    # post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end
end

app/views/elements/_footer.html.slim
footer
  .row
    .col-lg-6.text-right Copyright © Pôle com' Ensimag 2015-#{Date.today.year}
    .col-lg-6
      - unless user_signed_in?
        ul
          li= link_to "Connexion asso", new_user_session_path(redirect_to: URI(request.original_url).path)
          li= link_to "Connexion admin", admin_root_path, 'data-turbolinks': false

app/views/elements/_navbar.html.slim
nav.navbar.navbar-fixed-top.navbar-inverse role="navigation"
  .container
    // Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle data-target="#navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to defined?(root_path) ? root_path : "#", class: "navbar-brand" do
        = image_tag "logo64.png", class: "navbar-logo"
        | Asso-Ensimag
    // Collect the nav links, forms, and other content for toggling
    #navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li= link_to "Blog", blog_posts_path
        li= link_to "Events", events_path
        - if current_user
          li= link_to "Partenaires", partners_path
        - else
          - cache(:navbar_partner_link) do
            - if any_partners
              li= link_to "Partenaires", partners_path
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            | Les assos
            b.caret
          ul.dropdown-menu
            - cache(:navbar_asso_list) do
              - all_assos.each do |asso|
                li= link_to asso.username, asso_path(asso)
            li.divider
            li= link_to "Toutes les assos", assos_path
      - if user_signed_in?
        ul.nav.navbar-nav.navbar-right
          li= link_to asso_path(current_user) do
            span.glyphicon.glyphicon-user
            span.navbar-right-nav-item-text
              |  #{current_user.username}
          li= link_to edit_user_registration_path do
            span.glyphicon.glyphicon-cog
            span.navbar-right-nav-item-text
              |  Compte
          li= link_to destroy_user_session_path(redirect_to: URI(request.original_url).path), method: :delete do
            span.glyphicon.glyphicon-log-out
            span.navbar-right-nav-item-text
              |  Déconnexion