config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  # Associations list
  get 'assos' => 'assos#index', as: :assos

  # Specific asso details
  get 'asso/:id(/page/:page)' => 'assos#show',   as: :asso
  put 'asso/:id'              => 'assos#update', as: :update_asso
  get 'asso/:id/edit'         => 'assos#edit',   as: :edit_asso

  # Asso blog
  resources :blog_posts, path: 'posts'

  # Partners
  get    'partners'          => 'partners#index', as: :partners
  post   'partners'          => 'partners#create'
  put    'partners/:id'      => 'partners#update',  as: :partner
  delete 'partners/:id'      => 'partners#destroy'
  get    'partners/new'      => 'partners#new',     as: :new_partner
  get    'partners/:id/edit' => 'partners#edit',    as: :edit_partner

  # Asso events
  get 'events/calendar'              => 'events#calendar',    as: :events_calendar
  get 'asso/:id/events(/page/:page)' => 'events#asso_events', as: :asso_events
  resources :events do
    get 'page/:page', :action => :index, :on => :collection
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    # Disable user signup
    # get    "signup"  => "users/registrations#new",    as: :new_user_registration
    # post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = BlogPost.published.limit(5)
    @assos = User.sample(3)
    @events = Event.published.coming.limit(3)
  end
end

app/views/home/index.html.slim
header#homeCarousel.carousel.slide data-ride="carousel"
  ol.carousel-indicators
    - @posts.each_with_index do |post, i|
      li data-slide-to="#{i}" data-target='#homeCarousel' class=(if i == 0 then 'active' end)
  .carousel-inner
    - @posts.each_with_index do |post, i|
      div class=(if i == 0 then 'item active' else 'item' end)
        .fill style="background-image:url('#{post.picture.homepage}');"
        .carousel-caption
          = link_to blog_post_path(post)
            h2= post.title
            small= truncate post.summary, length: 50
  a.left.carousel-control data-slide="prev" href="#homeCarousel"
    span.icon-prev
  a.right.carousel-control data-slide="next" href="#homeCarousel"
    span.icon-next

.container
  .row
    h1.page-header Bienvenue sur Asso-Ensimag !
    p Ce site, créé et maintenu par le #{link_to "Pôle com'", asso_path('pole-com')}, rassemble toutes les associations
      de l'Ensimag. Tu pourras y trouver des articles postés par chaque asso, un calendrier des évents organisés par
      celles-ci et si cela ne suffit pas, de quoi les contacter.
  - if @events.length > 0
    .row
      h1.page-header Les évènements à venir
      .row
        - @events.each do |event|
          .col-md-4.img-portfolio
            = link_to event_path(event) do
              img.img-responsive.img-hover src="#{event.picture.list}"
            h3
              = link_to event.name, event_path(event)
              small
                = fa_icon "clock-o"
                = " #{distance_of_time_in_words(DateTime.now, event.start_time)}"
              small
                = fa_icon "map-marker"
                = " #{event.location}"
            p= descriptive_blob(event)
            em.faded Organisé par #{link_to event.asso.username, asso_events_path(event.asso)}
        - if @events.length == 1
          .col-md-4.img-portfolio
        - if @events.length < 3
          .col-md-4.text-center.no-more-events
            em Aucun autre évènement à venir
      .row
        = link_to "Tous les events", events_path, class: "btn btn-block btn-primary btn-lg"
  .row
    h1.page-header Quelques assos
    .row
      - @assos.each do |asso|
        = render partial: 'assos/asso_item', locals: { asso: asso }
    .row
      = link_to "Toutes les assos", assos_path, class: "btn btn-block btn-primary btn-lg"