config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  # Associations list
  get 'assos' => 'assos#index', as: :assos

  # Specific asso details
  get 'asso/:id(/page/:page)' => 'assos#show',   as: :asso
  put 'asso/:id'              => 'assos#update', as: :update_asso
  get 'asso/:id/edit'         => 'assos#edit',   as: :edit_asso

  # Asso blog
  resources :blog_posts, path: 'posts'

  # Partners
  get    'partners'          => 'partners#index', as: :partners
  post   'partners'          => 'partners#create'
  put    'partners/:id'      => 'partners#update',  as: :partner
  delete 'partners/:id'      => 'partners#destroy'
  get    'partners/new'      => 'partners#new',     as: :new_partner
  get    'partners/:id/edit' => 'partners#edit',    as: :edit_partner

  # Asso events
  get 'events/calendar'              => 'events#calendar',    as: :events_calendar
  get 'asso/:id/events(/page/:page)' => 'events#asso_events', as: :asso_events
  resources :events do
    get 'page/:page', :action => :index, :on => :collection
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    # Disable user signup
    # get    "signup"  => "users/registrations#new",    as: :new_user_registration
    # post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  # Friendly URL generation
  include FakeSlug
  fake_slug_uses :id, :name

  # Fetches the next events (for these, passed? == false)
  scope :coming, -> { where('end_time >= ?', DateTime.now).order(:start_time) }
  scope :passed, -> { where('end_time < ?',  DateTime.now).order(start_time: :desc) }

  # Fetches the events ordered by their start_time
  scope :ordered, -> { order(start_time: :desc) }

  # Returns only published events
  scope :published, -> (user = nil) { q = joins(:asso)
                                      if user.nil?
                                        q.where('published <= ? AND users.order IS NOT NULL', DateTime.now)
                                      else
                                        q.where('asso_id = :id OR (published <= :date AND users.order IS NOT NULL)',
                                                id: user.id, date: DateTime.now)
                                      end }

  # Relation to users
  belongs_to :asso, class_name: 'User', foreign_key: 'asso_id'

  # Indicates if the event has passed
  def passed?
    DateTime.now > end_time
  end

  def coming?
    DateTime.now < start_time
  end

  def duration
    end_time - start_time
  end

  # Fix for published time formatting
  include DatetimeAttributes
  datetime_attribute :start_time, :end_time

  # Kaminari pagination
  paginates_per 15

  mount_uploader :picture, EventPictureUploader

  # Validation attributes
  validates :name, :location, :description, :asso, presence: true
  validates :start_time, date: true
  validates :end_time, date: { after: :start_time }
  validates :facebook_url, url: { allow_nil: true, allow_blank: true, message: I18n.t('errors.messages.url') }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [ :show, :edit, :update, :destroy ]

  # GET /events(/page/:page)
  def index
    @events = Event.coming.published(current_user).page(params[:page])
  end

  # GET /events/calendar
  def calendar
    respond_to do |format|
      # Respond with calendar page HTML
      format.html
      # Respond with events in range as JSON
      format.json do
        if params[:to] and params[:from]
          date_to = DateTime.strptime(params[:to], '%Q')
          date_from = DateTime.strptime(params[:from], '%Q')
          @events = Event.published(current_user).where('start_time >= :start OR end_time <= :end OR (start_time < :start AND end_time > :end)',
                                                        start: date_from, end: date_to)
          @success = 1
        else
          @success = 0
        end
      end
      # Respond with CSS with event classes for users
      format.css
    end
  end

  # GET /asso/:id/events(/page/:page)?passed
  def asso_events
    @asso = User.friendly.find(params[:id])

    if params[:passed]
      @events = @asso.events.passed.published(current_user)
      @passed_events = true
    else
      @events = @asso.events.coming.published(current_user)
      @passed_events = false
    end

    @events = @events.page(params[:page])
  end

  # GET /events/1
  def show
    unless request.original_fullpath == event_path(@event)
      redirect_to event_path(@event)
    end
  end

  # GET /events/new
  def new
    @event = Event.new(asso: current_user)
    @asso = @event.asso

    # Authorize the event
    authorize_event
  end

  # GET /events/1/edit
  def edit
    @asso = @event.asso

    # Authorize the event
    authorize_event
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    # Users can only update their own events, so the current_user is the owner
    # of this event
    @event.asso = current_user

    # Set published datetime
    @event.published ||= DateTime.now

    # Authorize the event
    authorize_event

    if @event.save
      redirect_to event_path(@event), notice: "L'évènement a été créé avec succès."
    else
      @asso = current_user
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    # Authorize the event
    authorize_event

    # Verify update params
    upd_params = event_params
    upd_params[:published] = DateTime.now if upd_params[:published].empty?

    if @event.update(upd_params)
      redirect_to @event, notice: "L'évènement a été mis à jour avec succès."
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    # Authorize the event
    authorize_event

    @event.destroy
    redirect_to events_url, notice: "L'évènement a été supprimé avec succès."
  end

  private
    def set_event
      @event = Event.published(current_user).find(params[:id])
    end

    def event_params
      params[:event].permit(:name, :published, :start_time, :end_time, :location, :description, :facebook_url, :picture)
    end

    def authorize_event
      authorize @event
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def sidebar_item_class(link, set_success = false)
    path = URI(request.original_url).path.gsub /\/page\/\d+$/, ''
    active = (link == path)
    "list-group-item #{active ? 'active' : ''} #{set_success and (not active) ? 'list-group-item-success' : ''}"
  end
end

app/views/events/_event_item.html.slim
.row
  .col-md-8
    = link_to event_path(event) do
      img.img-responsive.img-hover src="#{event.picture.list}"
  .col-md-4
    h3= event.name
    .faded
      p
        = fa_icon "clock-o"
        = " "
        = time_tag event.start_time
      p
        = fa_icon "map-marker"
        = " #{event.location}"
      - unless hide_asso
        p
          = fa_icon "users"
          = " "
          = link_to event.asso.username, asso_path(event.asso)
    p
      = descriptive_blob(event, 120 + (hide_asso ? 30 : 0))
      = " "
      = link_to "Plus d'infos", event_path(event)
hr

app/views/events/_events_sidebar.html.slim
.list-group
  = link_to "A venir", events_path, class: sidebar_item_class(events_path, true)
  = link_to "Calendrier", events_calendar_path, class: sidebar_item_class(events_calendar_path, true)
  - all_assos.each do |asso|
    = link_to asso.username, asso_events_path(asso), class: sidebar_item_class(asso_events_path(asso))
= render partial: "assos/action_links", locals: { asso: current_user }

app/views/events/_form.html.slim
= simple_form_for(event, url: form_url, html: { method: form_method }) do |f|
  .col-lg-8
    = f.error_notification
    .form-inputs
      = f.input :name, required: true
      = f.input :published, as: :date_time_picker, required: true
      = f.input :start_time, as: :date_time_picker, required: true
      = f.input :end_time, as: :date_time_picker, required: true
      = f.input :location, required: true
      = f.input :facebook_url, required: false
      = f.input :description, as: :ckeditor, required: true, input_html: { ckeditor: { 'customConfig' => asset_path('ckeditor/config.js') }}
      = f.input :picture, as: :picture
  .col-md-4
    .well
      h4 Actions
      .form-actions
        = f.button :submit, class: 'btn btn-primary'
        - if event.id
          = link_to "Supprimer", event_path(event), method: :delete,
            data:  { confirm: "Voulez-vous vraiment supprimer cet event ? Cette opération est irréversible." },
            class: 'btn btn-danger btn-left-margin'
          = link_to "Annuler", event_path(event), class: 'btn btn-default btn-left-margin'
        - else
          = link_to "Annuler", asso_events_path(asso), class: 'btn btn-default btn-left-margin'

app/views/events/asso_events.html.slim
- title "#{@asso.username} - Events"
.container
  .row
    h1.page-header
      = @asso.username
      small
        | Events
        small
          | Ajourd'hui :
          = time_tag Date.today
    ol.breadcrumb
      li= link_to "Accueil", root_path
      li= link_to "Associations", assos_path
      li= link_to @asso.username, asso_path(@asso)
      li.active Events

  .row
    .col-md-9
      - has_seen_events = false
      - @events.each do |event|
        - has_seen_events = true
        = render partial: "event_item", locals: { event: event, hide_asso: true }
      - if has_seen_events
        = paginate @events
      - else
        .text-center
          - if @passed_events
            em Aucun event passé
          - else
            em Aucun event à venir
    .col-md-3
      = render partial: "events_sidebar"
      .well
        - if @passed_events
          = link_to "Events à venir", asso_events_path(@asso)
        - else
          = link_to "Events passés", asso_events_path(@asso, passed: true)
      = render partial: "assos/about_block", locals: { asso: @asso }

app/views/events/calendar.css.erb
<% all_assos.each do |asso| %>
<% bg_color = asso.color.paint.lighten(60).desaturate(50) %>
#cal-day-box .day-highlight.dh-event-<%= asso.to_param %> {
  border: 1px solid <%= bg_color %>;
}
.event-<%= asso.to_param %> {
  background-color: <%= asso.color %>;
}
.day-highlight.dh-event-<%= asso.to_param %>:hover,
.day-highlight.dh-event-<%= asso.to_param %> {
  background-color: <%= bg_color %>;
}
<% end %>

app/views/events/calendar.html.slim
= content_for :head
  = javascript_include_tag 'calendar',          'data-turbolinks-track' => true
  = stylesheet_link_tag '/events/calendar.css', 'data-turbolinks-track' => true

- title "Calendrier des events"
.container
  .row
    h1.page-header
      | Events
      small
        | Calendrier
        small
          | Ajourd'hui :
          = time_tag Date.today
    ol.breadcrumb
      li= link_to "Accueil", root_path
      li.active= content_for :title

  .row
    .col-md-9
      .calendar-controls
        .pull-right.form-inline
          .btn-group
            button.btn.btn-primary data-calendar-nav="prev" &lt; Précédent
            button.btn.btn-default data-calendar-nav="today" Ajourd'hui
            button.btn.btn-primary data-calendar-nav="next" Suivant &gt;
          .btn-group
            button.btn.btn-warning data-calendar-view="year" Année
            button.btn.btn-warning.active data-calendar-view="month" Mois
            button.btn.btn-warning data-calendar-view="week" Semaine
            button.btn.btn-warning data-calendar-view="day" Journée
        .clearfix
      h2.calendar-title.page-header
      .calendar data-events-source=events_calendar_path(:json)
    .col-md-3
      = render partial: "events_sidebar"

app/views/events/edit.html.slim
.container
  .row
    h1.page-header= title "Edition de l'event \"#{@event.name}\""
    ol.breadcrumb
      li= link_to "Accueil", root_path
      li= link_to "Associations", assos_path
      li= link_to @asso.username, asso_path(@asso)
      li= link_to "Events", asso_events_path(@asso)
      li= link_to @event.name, event_path(@event)
      li.active Edition

  .row
    = render partial: 'form', locals: { event: @event,
                                        asso: @asso,
                                        form_url: event_path(@event),
                                        form_method: :put }

app/views/events/index.html.slim
- title "Events à venir"
.container
  .row
    h1.page-header
      | Events
      small
        | A venir
        small
          | Ajourd'hui :
          = time_tag Date.today
    ol.breadcrumb
      li= link_to "Accueil", root_path
      li.active= content_for :title

  .row
    .col-md-9
      - has_seen_events = false
      - @events.each do |event|
        - has_seen_events = true
        = render partial: "event_item", locals: {event: event, hide_asso: false }
      - if has_seen_events
        = paginate @events
      - else
        .text-center
          em Aucun event à venir
    .col-md-3
      = render partial: "events_sidebar"

app/views/events/new.html.slim
.container
  .row
    h1.page-header= title "Nouvel event"
    ol.breadcrumb
      li= link_to "Accueil", root_path
      li= link_to "Associations", assos_path
      li= link_to @asso.username, asso_path(@asso)
      li= link_to "Events", asso_events_path(@asso)
      li.active Nouvel event

  .row
    = render partial: 'form', locals: { event: @event,
                                        asso: @asso,
                                        form_url: events_path,
                                        form_method: :post }

app/views/events/show.html.slim
.container
  .row
    h1.page-header
      = title @event.name
      small Organisé par #{link_to @event.asso.username, asso_path(@event.asso)}
  ol.breadcrumb
    li= link_to "Accueil", root_path
    li= link_to "Associations", assos_path
    li= link_to @event.asso.username, asso_path(@event.asso)
    li= link_to "Events", asso_events_path(@event.asso)
    li.active= @event.name

  .row
    .col-md-4
      .well
        h4 Détails de l'évènement
        .indented
          p
            = fa_icon "clock-o"
            = " "
            = time_tag @event.start_time
            br
            = fa_icon "long-arrow-right"
            = " "
            = time_tag @event.end_time
          p
            = fa_icon "map-marker"
            = " "
            = @event.location
          - if @event.facebook_url
            p
              = fa_icon "facebook-official"
              = " "
              = link_to "Page de l'évènement", @event.facebook_url
        - if can_edit(@event)
          h4 Actions
          = link_to "Modifier l'event", edit_event_path(@event), class: 'btn btn-primary btn-block'
      = render partial: "assos/social_block", locals: { asso: @event.asso }
      = render partial: "assos/about_block", locals: { asso: @event.asso }
    .col-lg-8
      = link_to @event.picture.to_s
        img.img-responsive.center-block src=@event.picture
      hr
      = rich_safe(@event.description)