config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  # Associations list
  get 'assos' => 'assos#index', as: :assos

  # Specific asso details
  get 'asso/:id(/page/:page)' => 'assos#show',   as: :asso
  put 'asso/:id'              => 'assos#update', as: :update_asso
  get 'asso/:id/edit'         => 'assos#edit',   as: :edit_asso

  # Asso blog
  resources :blog_posts, path: 'posts'

  # Partners
  get    'partners'          => 'partners#index', as: :partners
  post   'partners'          => 'partners#create'
  put    'partners/:id'      => 'partners#update',  as: :partner
  delete 'partners/:id'      => 'partners#destroy'
  get    'partners/new'      => 'partners#new',     as: :new_partner
  get    'partners/:id/edit' => 'partners#edit',    as: :edit_partner

  # Asso events
  get 'events/calendar'              => 'events#calendar',    as: :events_calendar
  get 'asso/:id/events(/page/:page)' => 'events#asso_events', as: :asso_events
  resources :events do
    get 'page/:page', :action => :index, :on => :collection
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    # Disable user signup
    # get    "signup"  => "users/registrations#new",    as: :new_user_registration
    # post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end
end

app/controllers/asso_controller.rb
class AssoController < ApplicationController
  before_action :set_asso, except: [ :index ]

  # GET /assos
  def index
    @assos = User.all
  end

  # GET /asso/:id
  def show
    @posts = ((current_user == @asso) ? @asso.posts : @asso.posts.published).page(params[:page])
  end

  # GET /asso/:id/detail
  def detail
  end

  # GET /asso/:id/edit
  def edit
  end

  # PUT /asso/:id
  def update
    if @asso.update(asso_params)
      redirect_to asso_path(@asso), flash: { notice: "Les modifications ont été enregistrées" }
    else
      render action: 'edit'
    end
  end

  protected
    def set_asso
      @asso = User.friendly.find(params[:id])
    end

    def asso_params
      params[:user].permit(:description, :facebook_url, :site_url, :color)
    end
end

app/controllers/assos_controller.rb
class AssosController < ApplicationController
  before_action :set_asso, except: [ :index ]

  # GET /assos
  def index
  end

  # GET /asso/:id
  def show
    @posts = @asso.posts.published(current_user).page(params[:page])
  end

  # GET /asso/:id/edit
  def edit
    authorize_asso
  end

  # PUT /asso/:id
  def update
    authorize_asso

    if @asso.update(asso_params)
      redirect_to asso_path(@asso), flash: { notice: "Les modifications ont été enregistrées" }
    else
      render action: 'edit'
    end
  end

  protected
    def set_asso
      @asso = User.friendly.find(params[:id])
    end

    def asso_params
      params[:user].permit(:description, :facebook_url, :site_url, :color, :picture)
    end

    def authorize_asso
      authorize @asso
    end
end

app/helpers/asso_helper.rb
module AssoHelper
  def can_edit(item)
    return false if item.nil?

    if item.is_a? User
      current_user == item
    elsif item.is_a? BlogPost
      current_user == item.author
    elsif item.is_a? Event
      current_user == item.asso
    else
      false
    end
  end

  def descriptive_blob(asso, len = 100)
    truncate (markdown_plain(asso.description) or "Pas de description"), length: len
  end
end

app/helpers/assos_helper.rb
module AssosHelper
  def can_edit(item)
    return false if item.nil?

    return policy(item).edit?
  end

  def descriptive_blob(asso, len = 150)
    truncate (rich_plain(asso.description) or "Pas de description"), length: len
  end
end

app/views/assos/_about_block.html.slim
.well
  h4 A propos
  = link_to asso_path(asso) do
    img.img-responsive.img-hover.center-block src="#{asso.picture.list}"
  p= descriptive_blob(asso)
  = link_to "En savoir plus", asso_path(asso), class: 'btn btn-default btn-block'

app/views/assos/_action_links.html.slim
- if can_edit(asso)
  .well
    h4 Actions
    = link_to "Nouvel article", new_blog_post_path, class: 'btn btn-primary btn-block'
    = link_to "Nouvel event", new_event_path, class: 'btn btn-primary btn-block'
    = link_to "Nouveau partenaire", new_partner_path, class: 'btn btn-primary btn-block'
    = link_to "Modifier l'asso", edit_asso_path(asso), class: 'btn btn-default btn-block'

app/views/assos/_asso_item.html.slim
.col-md-4.img-portfolio
  = link_to asso_path(asso) do
    img.img-responsive.img-hover.center-block src="#{asso.picture.list}"
  h3= link_to asso.username, asso_path(asso)
  p= descriptive_blob(asso)

app/views/assos/_event_block.html.slim
.well
  - if asso.next_event.nil?
    em Aucun évènement à venir
  - else
    h4
      = asso.next_event.name
    .faded
      p
        = fa_icon "clock-o"
        = " "
        = time_tag asso.next_event.start_time
      p
        = fa_icon "map-marker"
        = " "
        = asso.next_event.location
      - if asso.next_event.facebook_url
        p
          = fa_icon "facebook-official"
          = " "
          = link_to "Page de l'évènement", asso.next_event.facebook_url
    p= descriptive_blob(asso.next_event)
    = link_to "Plus d'infos", event_path(asso.next_event), class: 'btn btn-default btn-block'

app/views/assos/_social_block.html.slim
.well
  h4 Contacter #{link_to asso.username, asso_path(asso)}
  p
    = fa_icon "envelope-o"
    span= " E-mail : "
    = mail_to asso.email, nil, replace_at: " [a] ", replace_dot: " [point] ", encode: :hex
  - unless asso.site_url.blank?
    p
      = fa_icon "globe"
      span= " Site web : "
      = link_to asso.site_url, asso.site_url
  - unless asso.facebook_url.blank?
    p
      = fa_icon "facebook-official"
      = " "
      = link_to "Page facebook", asso.facebook_url

app/views/assos/edit.html.slim
.container
  .row
    h1.page-header= title "Modifier l'asso #{@asso.username}"
    ol.breadcrumb
      li= link_to "Accueil", root_path
      li= link_to "Associations", assos_path
      li= link_to @asso.username, asso_path(@asso)
      li.active Modifier

  .row
    = simple_form_for(@asso, url: update_asso_path(@asso), html: { method: :put }) do |f|
      = f.error_notification
      .form-inputs
        = f.input :site_url
        = f.input :facebook_url
        = f.input :color, input_html: { class: 'colorpicker-editor' }
        = f.input :description, as: :ckeditor, input_html: { ckeditor: { 'customConfig' => asset_path('ckeditor/config.js') }}
        = f.input :picture, as: :picture
      .form-actions
        = f.button :submit, class: 'btn btn-primary'

app/views/assos/index.html.slim
.container
  .row
    h1.page-header= title "Les associations de l'Ensimag"
    ol.breadcrumb
      li= link_to "Accueil", root_path
      li.active Associations

  .row
    - all_assos.each_with_index.each do |asso, i|
      = render partial: "asso_item", locals: { asso: asso }
      - if ((i + 1) % 3) == 0
        .clearfix

app/views/assos/show.html.slim
.container
  .row
    h1.page-header
      = title @asso.username
      small A propos
    ol.breadcrumb
      li= link_to "Accueil", root_path
      li= link_to "Associations", assos_path
      li.active= @asso.username

  .row
    .col-md-8
      = link_to @asso.picture.to_s do
        img.img-responsive.center-block src=@asso.picture
      hr
      = rich_safe(@asso.description) or "Cette association n'a pas encore édité sa description."
    .col-md-4
      = render partial: "event_block", locals: {asso: @asso}
      = render partial: "action_links", locals: {asso: @asso}
      = render partial: "social_block", locals: {asso: @asso}